language: ruby
rvm:
  - 2.3
addons:
  chrome: stable
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - bundle install
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rake
